Repository kottans/frontend-2019-p2p, pull requests merged in 2019-10, with the labels that each got.

#100 COMPLETE HTML and CSS practice
  submissions/karelskiy/HTML and CSS practice/LICENSE
  submissions/karelskiy/HTML and CSS practice/README.md
  submissions/karelskiy/HTML and CSS practice/img/JhonDoe.jpg
  submissions/karelskiy/HTML and CSS practice/img/crunchyroll.png
  submissions/karelskiy/HTML and CSS practice/img/discord-logo.png
  submissions/karelskiy/HTML and CSS practice/img/facebook-new.png
  submissions/karelskiy/HTML and CSS practice/img/flickr.png
  submissions/karelskiy/HTML and CSS practice/img/icons8-материал-sharp-96 (3).png
  submissions/karelskiy/HTML and CSS practice/img/instagram.png
  submissions/karelskiy/HTML and CSS practice/img/line-me.png
  submissions/karelskiy/HTML and CSS practice/img/linkedin.png
  submissions/karelskiy/HTML and CSS practice/img/msg.png
  submissions/karelskiy/HTML and CSS practice/img/pinterest.png
  submissions/karelskiy/HTML and CSS practice/img/skype.png
  submissions/karelskiy/HTML and CSS practice/img/snapchat.png
  submissions/karelskiy/HTML and CSS practice/img/telegram-app.png
  submissions/karelskiy/HTML and CSS practice/img/whatsapp.png
  submissions/karelskiy/HTML and CSS practice/img/xing.png
  submissions/karelskiy/HTML and CSS practice/img/youtube.png
  submissions/karelskiy/HTML and CSS practice/index.html
  submissions/karelskiy/HTML and CSS practice/style.css
Labels: task-PopUp

#75 js-dom-task
  submissions/ArthurGorbenko/js-dom/README.md
  submissions/ArthurGorbenko/js-dom/css/style.css
  submissions/ArthurGorbenko/js-dom/images/Saint-Bernard-Puppies.jpg
  submissions/ArthurGorbenko/js-dom/images/chaochao.jpg
  submissions/ArthurGorbenko/js-dom/images/doberman.jpg
  submissions/ArthurGorbenko/js-dom/images/labrador.jpg
  submissions/ArthurGorbenko/js-dom/images/startPhoto.jpg
  submissions/ArthurGorbenko/js-dom/images/terrier.jpg
  submissions/ArthurGorbenko/js-dom/index.html
  submissions/ArthurGorbenko/js-dom/script.js
Labels: task-DOM

#76 Tiny-Js-World
  submissions/ArthurGorbenko/tiny-js-world/index.js
Labels: task-TJSW

#79 Frogger game
  submissions/ArthurGorbenko/frogger-game/README.md
  submissions/ArthurGorbenko/frogger-game/css/style.css
  submissions/ArthurGorbenko/frogger-game/images/Gem Blue.png
  submissions/ArthurGorbenko/frogger-game/images/Gem Green.png
  submissions/ArthurGorbenko/frogger-game/images/Gem Orange.png
  submissions/ArthurGorbenko/frogger-game/images/Heart.png
  submissions/ArthurGorbenko/frogger-game/images/Key.png
  submissions/ArthurGorbenko/frogger-game/images/Rock.png
  submissions/ArthurGorbenko/frogger-game/images/Selector.png
  submissions/ArthurGorbenko/frogger-game/images/Star.png
  submissions/ArthurGorbenko/frogger-game/images/char-boy.png
  submissions/ArthurGorbenko/frogger-game/images/char-cat-girl.png
  submissions/ArthurGorbenko/frogger-game/images/char-horn-girl.png
  submissions/ArthurGorbenko/frogger-game/images/char-pink-girl.png
  submissions/ArthurGorbenko/frogger-game/images/char-princess-girl.png
  submissions/ArthurGorbenko/frogger-game/images/enemy-bug.png
  submissions/ArthurGorbenko/frogger-game/images/grass-block.png
  submissions/ArthurGorbenko/frogger-game/images/stone-block.png
  submissions/ArthurGorbenko/frogger-game/images/water-block.png
  submissions/ArthurGorbenko/frogger-game/index.html
  submissions/ArthurGorbenko/frogger-game/js/app.js
  submissions/ArthurGorbenko/frogger-game/js/engine.js
  submissions/ArthurGorbenko/frogger-game/js/resources.js
Labels: task-Frogger

#81 Memory pair game
  submissions/ArthurGorbenko/Memory Pair Game/README.md
  submissions/ArthurGorbenko/Memory Pair Game/css/styles.css
  submissions/ArthurGorbenko/Memory Pair Game/images/redkie.jpg
  submissions/ArthurGorbenko/Memory Pair Game/index.html
  submissions/ArthurGorbenko/Memory Pair Game/js/script.js
Labels: task-MPG

#83 Friend's app
  submissions/ArthurGorbenko/Friend's app/README.md
  submissions/ArthurGorbenko/Friend's app/css/hamburgers.css
  submissions/ArthurGorbenko/Friend's app/css/styles.css
  submissions/ArthurGorbenko/Friend's app/index.html
  submissions/ArthurGorbenko/Friend's app/js/script.js
Labels: task-Friends

#84 HTML-CSS-PopUp
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/alarm.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/avatar.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/bell.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/book.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/calendar.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/chat.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/cloud.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/docs.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/dots.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/mail.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/movie.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/music.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/notes.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/photo.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/store.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/timer.png
  submissions/NastjonkaK/HTML-CSS-Popup/Icons/translate.png
  submissions/NastjonkaK/HTML-CSS-Popup/Style/style.css
  submissions/NastjonkaK/HTML-CSS-Popup/index.html
Labels: task-PopUp

#87 React friends app
  submissions/Zakkarat/simple-react-app/src/App/App.css
  submissions/Zakkarat/simple-react-app/src/App/App.js
  submissions/Zakkarat/simple-react-app/src/App/App.test.js
  submissions/Zakkarat/simple-react-app/src/CardContainer/Card.js
  submissions/Zakkarat/simple-react-app/src/CardContainer/CardContainer.css
  submissions/Zakkarat/simple-react-app/src/CardContainer/CardContainer.js
  submissions/Zakkarat/simple-react-app/src/CardContainer/Pagination.js
  submissions/Zakkarat/simple-react-app/src/CardContainer/Select.js
  submissions/Zakkarat/simple-react-app/src/CardContainer/SelectOptions.js
  submissions/Zakkarat/simple-react-app/src/FilterBar/FilterBar.css
  submissions/Zakkarat/simple-react-app/src/FilterBar/FilterBar.js
  submissions/Zakkarat/simple-react-app/src/index.css
  submissions/Zakkarat/simple-react-app/src/index.js
  submissions/Zakkarat/simple-react-app/src/logo.svg
  submissions/Zakkarat/simple-react-app/src/serviceWorker.js
Labels: React-App

#90 Frogger game
  submissions/mfialko/js-oop/README.md
  submissions/mfialko/js-oop/css/style.css
  submissions/mfialko/js-oop/images/Gem Blue.png
  submissions/mfialko/js-oop/images/Gem Green.png
  submissions/mfialko/js-oop/images/GemOrange.png
  submissions/mfialko/js-oop/images/Heart.png
  submissions/mfialko/js-oop/images/Key.png
  submissions/mfialko/js-oop/images/Rock.png
  submissions/mfialko/js-oop/images/Selector.png
  submissions/mfialko/js-oop/images/Star.png
  submissions/mfialko/js-oop/images/char-boy.png
  submissions/mfialko/js-oop/images/char-cat-girl.png
  submissions/mfialko/js-oop/images/char-horn-girl.png
  submissions/mfialko/js-oop/images/char-pink-girl.png
  submissions/mfialko/js-oop/images/char-princess-girl.png
  submissions/mfialko/js-oop/images/enemy-bug.png
  submissions/mfialko/js-oop/images/grass-block.png
  submissions/mfialko/js-oop/images/stone-block.png
  submissions/mfialko/js-oop/images/water-block.png
  submissions/mfialko/js-oop/index.html
  submissions/mfialko/js-oop/js/app.js
  submissions/mfialko/js-oop/js/engine.js
  submissions/mfialko/js-oop/js/resources.js
Labels: task-Frogger

#105 tiny js world without oop
  submissions/karelskiy/tiny-JS-world/index.js
Labels: task-TJSW
