Repository kottans/frontend-2019-p2p, pull requests merged in 2019-06, with the labels that each got.

#69 Html forms
  submissions/Zakkarat/html-forms/index.html
  submissions/Zakkarat/html-forms/stylesheet/choose-document.css
  submissions/Zakkarat/html-forms/stylesheet/footer.css
  submissions/Zakkarat/html-forms/stylesheet/header.css
  submissions/Zakkarat/html-forms/stylesheet/language-choose.css
  submissions/Zakkarat/html-forms/stylesheet/main.css
  submissions/Zakkarat/html-forms/stylesheet/normalize.css
  submissions/Zakkarat/html-forms/stylesheet/payment.css
  submissions/Zakkarat/html-forms/stylesheet/tone-time.css
  submissions/Zakkarat/html-forms/stylesheet/upload.css
Labels: task -HTMLForm

#77 friends-app
  submissions/sayckl/friends-app/index.html
  submissions/sayckl/friends-app/script.js
  submissions/sayckl/friends-app/style.css
Labels: task-Friends

#67 Html css practice
  README.md
  submissions/ArthurGorbenko/html.css.practice/README.md
  submissions/ArthurGorbenko/html.css.practice/account.png
  submissions/ArthurGorbenko/html.css.practice/app_market.png
  submissions/ArthurGorbenko/html.css.practice/blog.png
  submissions/ArthurGorbenko/html.css.practice/bookmarks.png
  submissions/ArthurGorbenko/html.css.practice/business.png
  submissions/ArthurGorbenko/html.css.practice/calendar.png
  submissions/ArthurGorbenko/html.css.practice/cloud_search.png
  submissions/ArthurGorbenko/html.css.practice/connections.png
  submissions/ArthurGorbenko/html.css.practice/contacts.png
  submissions/ArthurGorbenko/html.css.practice/css/sprites.png
  submissions/ArthurGorbenko/html.css.practice/css/styles.css
  submissions/ArthurGorbenko/html.css.practice/documents.png
  submissions/ArthurGorbenko/html.css.practice/drive.png
  submissions/ArthurGorbenko/html.css.practice/earth.png
  submissions/ArthurGorbenko/html.css.practice/gmail.png
  submissions/ArthurGorbenko/html.css.practice/index.html
  submissions/ArthurGorbenko/html.css.practice/maps.png
  submissions/ArthurGorbenko/html.css.practice/news.png
  submissions/ArthurGorbenko/html.css.practice/notification.png
  submissions/ArthurGorbenko/html.css.practice/office_apps.png
  submissions/ArthurGorbenko/html.css.practice/options.png
  submissions/ArthurGorbenko/html.css.practice/profile_picture.png
  submissions/ArthurGorbenko/html.css.practice/qouotes.png
  submissions/ArthurGorbenko/html.css.practice/security.png
  submissions/ArthurGorbenko/html.css.practice/tickets.png
  submissions/ArthurGorbenko/html.css.practice/translate.png
  submissions/ArthurGorbenko/html.css.practice/video.png
  submissions/ArthurGorbenko/html.css.practice/videoeditor.png
  submissions/ArthurGorbenko/html.css.practice/youTube.png
Labels: task-PopUp
