Repository kottans/frontend-2019-p2p, pull requests merged in 2019-02, with the labels that each got.

#20 a-tiny-JS-world-oop done
  submissions/Roka20012/a-tiny-JS-world-oop/index.js
Labels: task-TJSW-OOP

#19 js-oop done
  submissions/Roka20012/js-oop/app.js
Labels: task-Frogger

#17 dom-practice-work
  submissions/korotushak96/js-dom/img/Augurey.jpg
  submissions/korotushak96/js-dom/img/Bowtruckle.png
  submissions/korotushak96/js-dom/img/Jarvey.png
  submissions/korotushak96/js-dom/img/Murtlap.jpg
  submissions/korotushak96/js-dom/img/niffler.png
  submissions/korotushak96/js-dom/img/nundu_by_bear_drool_dbd2elu-pre.png
  submissions/korotushak96/js-dom/index.css
  submissions/korotushak96/js-dom/index.html
  submissions/korotushak96/js-dom/script.js
Labels: task-DOM

#25 Tiny JS world
  submissions/Zakkarat/a-tiny-JS-world/index.js
Labels: task-TJSW

#24 dom-api-task
  submissions/Zakkarat/js-dom/app.js
  submissions/Zakkarat/js-dom/index.html
  submissions/Zakkarat/js-dom/stylesheet/hamburger.css
  submissions/Zakkarat/js-dom/stylesheet/main.css
Labels: task-DOM

#22 tiny JS world --done
  submissions/korotushak96/a-tiny-JS-world/index.js
Labels: task-TJSW

#29 memory-pair-game done
  submissions/Roka20012/memory-pair-game/index.html
  submissions/Roka20012/memory-pair-game/js/script.js
  submissions/Roka20012/memory-pair-game/style.css
Labels: task-MPG

#16 Created tiny-js-world
  submissions/mxmgny/a-tiny-js-world/index.js
Labels: task-TJSW

#30 JS-OOP
  submissions/Zakkarat/JS-OOP/css/style.css
  submissions/Zakkarat/JS-OOP/index.html
  submissions/Zakkarat/JS-OOP/js/app.js
Labels: task-Frogger

#35 memory-pair-game --done
  submissions/korotushak96/memory-pair-game/css/style.css
  submissions/korotushak96/memory-pair-game/index.html
  submissions/korotushak96/memory-pair-game/js/script.js
Labels: task-MPG

#37 simple google page
  submissions/madmaxWMFU/google-popup/css/style.css
  submissions/madmaxWMFU/google-popup/img/account.jpg
  submissions/madmaxWMFU/google-popup/img/allIcons.png
  submissions/madmaxWMFU/google-popup/img/anotherIcons.png
  submissions/madmaxWMFU/google-popup/img/keep.png
  submissions/madmaxWMFU/google-popup/img/logo.png
  submissions/madmaxWMFU/google-popup/img/mic.png
  submissions/madmaxWMFU/google-popup/img/monkey.png
  submissions/madmaxWMFU/google-popup/img/myAccount.png
  submissions/madmaxWMFU/google-popup/img/tia.png
  submissions/madmaxWMFU/google-popup/index.html
Labels: task-PopUp

#36 Memory Pair Game
  submissions/Zakkarat/memory-pair-game/app.js
  submissions/Zakkarat/memory-pair-game/index.html
  submissions/Zakkarat/memory-pair-game/stylesheet/main.css
Labels: task-MPG

#31 pop up menu
  submissions/Roka20012/pop-up-menu/index.pug
  submissions/Roka20012/pop-up-menu/style.scss
Labels: task-PopUp

#34 html_css_popup
  submissions/Temu4/html_css_popup/README.md
  submissions/Temu4/html_css_popup/img/apps-acc.png
  submissions/Temu4/html_css_popup/img/apps-blogger.png
  submissions/Temu4/html_css_popup/img/apps-booble+.png
  submissions/Temu4/html_css_popup/img/apps-bussines.png
  submissions/Temu4/html_css_popup/img/apps-classroom.png
  submissions/Temu4/html_css_popup/img/apps-collection.png
  submissions/Temu4/html_css_popup/img/apps-contact.png
  submissions/Temu4/html_css_popup/img/apps-dairy.png
  submissions/Temu4/html_css_popup/img/apps-disk.png
  submissions/Temu4/html_css_popup/img/apps-docs.png
  submissions/Temu4/html_css_popup/img/apps-earth.png
  submissions/Temu4/html_css_popup/img/apps-jumboard.png
  submissions/Temu4/html_css_popup/img/apps-keep.png
  submissions/Temu4/html_css_popup/img/apps-mail.png
  submissions/Temu4/html_css_popup/img/apps-map.png
  submissions/Temu4/html_css_popup/img/apps-market.png
  submissions/Temu4/html_css_popup/img/apps-massager.png
  submissions/Temu4/html_css_popup/img/apps-photos.png
  submissions/Temu4/html_css_popup/img/apps-search.png
  submissions/Temu4/html_css_popup/img/apps-translate.png
  submissions/Temu4/html_css_popup/img/apps-tube.png
  submissions/Temu4/html_css_popup/img/icon-apps.png
  submissions/Temu4/html_css_popup/img/icon-bell.png
  submissions/Temu4/html_css_popup/img/icon-logo.png
  submissions/Temu4/html_css_popup/img/voice-search.png
  submissions/Temu4/html_css_popup/index.html
  submissions/Temu4/html_css_popup/style.css
Labels: task-PopUp
